baseURL = "//jacobobedoya.com/"
languageCode = "en-us"
title = "jacobitosuperstar"
assetDir = "static/assets/"
DefaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
summaryLength = 70
staticDir = "static"

[languages]
  [languages.es]
    languageName = "Espa√±ol"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    # style = 'vim'
    style = 'modus-vivendi'
    tabWidth = 4

[permalinks]
  404 = "/404/"

[params]
  email = "jacobobedoya@gmail.com"
  codeberg = "https://codeberg.org/jacobitosuperstar"
  linkedin = "https://www.linkedin.com/in/jmbo/"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
